#!/bin/bash

NCCL_SOCKET_IFNAME=lo deepspeed llava/ego4o/train/train_mem_ego4o.py \
    --load_motion_encoder False \
    --freeze_motion_encoder True \
    --deepspeed ./scripts/zero3_offload.json \
    --model_name_or_path /CT/EgoMocap/work/LLaVA/checkpoints/ego4o_motion2text_pretrain \
    --version v1 \
    --data_path /scratch/inf0/user/jianwang/nymeria/ego4o_input_json.jsonl \
    --image_folder /scratch/inf0/user/jianwang/nymeria/dummy_image \
    --motion_folder /scratch/inf0/user/jianwang/nymeria/ego4o_input_motion \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/debug_motion_to_text_finetune \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
